tags:
  - "APIs"
summary: "send prediction data"
description: "Enter all data in given format, for the model to predict"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "Data"
  description: "Paramaters required for predicting"
  required: true
  schema:
    type: "object"
    properties:
      over:
        type: "integer"
        format: "int64"
        example : 7
      wickets:
        type: "integer"
        format: "int64"
        example : 0
      runs:
        type: "integer"
        format: "int64"
        example : 52
      last_5_over_wickets:
        type: "integer"
        format: "int64"
        example : 0
      last_5_over_runs:
        type: "integer"
        format: "int64"
        example : 24
      batting_team:
        type: "string"
        example : "Sunrisers Hyderabad"
      bowling_team:
        type: "string"
        example : "Delhi Capitals"
      venue:
        type: "string"
        example : "Sheikh Zayed Stadium"
definitions:
  Result:
    type: object
    properties:
      score:
        type: integer
        example: 150
  Error:
    type: object 
    properties:
      Error:
        type: string
        example: invalid input

responses:
  200:
    description: "ok"
    schema:
      $ref: '#/definitions/Result'
  
  400:
    description: "Bad Request"
    schema:
      $ref: '#/definitions/Error'
